[package]
name = "decentra-bevy"
version = "0.1.0"
edition = "2021"

[features]
dcl-assert = []
gen-tests = []
tracy = ["bevy/trace_tracy"]

[workspace]
members = ["crates/*"]

[dependencies]
common = "0.1"
avatar = "0.1"
comms = "0.1"
input_manager = "0.1"
ipfs = "0.1"
system_ui = "0.1"
user_input = "0.1"
visuals = "0.1"
ui_core = "0.1"
scene_runner = "0.1"
console = "0.1"

bevy = "0.10"
bevy_console = "0.7.0"
bevy_prototype_debug_lines = { version = "0.10.1", features = ["3d"] }
bevy_mod_billboard = "0.3"

serde = "1.0.152"
serde_json = { version = "1.0.92", features = ["raw_value"] }
pico-args = "0.5.0"
clap = "4.1.10"

[build-dependencies]
prost-build = "0.11.8"

[patch.crates-io]
bevy = { git="https://github.com/robtfm/bevy", branch="0.10-hotfix" }

common = { path="./crates/common" }
avatar = { path="./crates/avatar" }
comms = { path="./crates/comms" }
console = { path="./crates/console" }
dcl = { path="./crates/dcl" }
dcl_component = { path="./crates/dcl_component" }
input_manager = { path="./crates/input_manager" }
ipfs = { path="./crates/ipfs" }
scene_runner = { path="./crates/scene_runner" }
system_ui = { path="./crates/system_ui" }
user_input = { path="./crates/user_input" }
visuals = { path="./crates/visuals" }
ui_core = { path="./crates/ui_core" }