[package]
name = "decentra-bevy"
version = "0.1.0"
edition = "2021"

[features]
dcl-assert = []
gen-tests = []
tracy = ["bevy/trace_tracy"]

[workspace]
members = ["crates/*"]

[dependencies]
common = { path="crates/common" }
avatar = { path="crates/avatar" }
comms = { path="crates/comms" }
input_manager = { path="crates/input_manager" }
ipfs = { path="crates/ipfs" }
system_ui = { path="crates/system_ui" }
user_input = { path="crates/user_input" }
visuals = { path="crates/visuals" }
ui_core = { path="crates/ui_core" }
scene_runner = { path="crates/scene_runner" }
console = { path="crates/console" }

bevy = "0.10"
bevy_console = "0.7.0"
bevy_prototype_debug_lines = { version = "0.10.1", features = ["3d"] }
bevy_mod_billboard = "0.3"

serde = "1.0.152"
serde_json = { version = "1.0.92", features = ["raw_value"] }
pico-args = "0.5.0"
clap = "4.1.10"

[build-dependencies]
prost-build = "0.11.8"

[patch.crates-io]
bevy = { git="https://github.com/robtfm/bevy", branch="0.10-hotfix" }
bevy_mod_billboard = { git="https://github.com/robtfm/bevy_mod_billboard", branch="lock_all" }