[package]
name = "decentra-bevy"
version = "0.1.0"
edition = "2021"

[features]
dcl-assert = []
gen-tests = []
tracy = ["bevy/trace_tracy"]
inspect = ["dcl/inspect"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
common = { path="crates/common" }
avatar = { path="crates/avatar" }
comms = { path="crates/comms" }
input_manager = { path="crates/input_manager" }
ipfs = { path="crates/ipfs" }
system_ui = { path="crates/system_ui" }
user_input = { path="crates/user_input" }
visuals = { path="crates/visuals" }
ui_core = { path="crates/ui_core" }
scene_runner = { path="crates/scene_runner" }
console = { path="crates/console" }
av = { path="crates/av" }
dcl = { path="crates/dcl" }
dcl_component = { path="crates/dcl_component" }
restricted_actions = { path="crates/restricted_actions" }
wallet = { path="crates/wallet" }
nft = { path="crates/nft" }

bevy = { version = "0.12", features=["jpeg"] }
bevy_console = { git = "https://github.com/msklosak/bevy-console", branch = "bevy_0.12_update" }
bevy_mod_billboard = { git = "https://github.com/robtfm/bevy_mod_billboard", branch = "bevy12" }
bevy_egui = "0.23"

serde = "1.0.152"
serde_json = { version = "1.0.92", features = ["raw_value"] }

tokio = { version = "1.29.1", features = ["sync"] }
anyhow = "1.0.70"
urn = "0.7.0"
ethers-signers = "2.0.3"
ethers-core = "2.0.3"
futures-lite = "1.12.0"
bimap = "0.6.3"
prost = "0.11.8"
clap = "4.1.10"
once_cell = "1.16.0"
rapier3d-f64 = "0.17.2"
urlencoding = "2.1.2"
async-std = "1.12.0"
# todo: use isahc 2.0 when it's released
isahc = { git = "https://github.com/sagebind/isahc", rev="096aff7b13f4ff5bb474fdc27bc30b297a2968f6", default-features = false, features = ["json", "text-decoding", "http2", "rustls-tls-native-certs"] }
kira = "0.8.4"
bevy_kira_audio = { git = "https://github.com/robtfm/bevy_kira_audio", branch = "pub-mod-12", features=["flac", "mp3", "ogg", "wav"] }

[dependencies]
common = { workspace = true }
avatar = { workspace = true }
comms = { workspace = true }
input_manager = { workspace = true }
ipfs = { workspace = true }
system_ui = { workspace = true }
user_input = { workspace = true }
visuals = { workspace = true }
ui_core = { workspace = true }
scene_runner = { workspace = true }
console = { workspace = true }
av = { workspace = true }
restricted_actions = { workspace = true }
wallet = { workspace = true }
dcl = { workspace = true }
nft = { workspace = true }

bevy = { workspace = true }
bevy_console = { workspace = true }
bevy_mod_billboard = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }

pico-args = "0.5.0"

[build-dependencies]
prost-build = "0.11.8"

[patch.crates-io]
bevy = { git = "https://github.com/robtfm/bevy", branch = "release-0.12-hotfix2" }
# bevy_kira_audio = { git = "https://github.com/robtfm/bevy_kira_audio", branch = "pub-manager" }
ffmpeg-next = { git = "https://github.com/robtfm/rust-ffmpeg", branch = "audio-linesize-0" }
parry3d-f64 = { git = "https://github.com/robtfm/parry", branch = "try_convex" }
rapier3d-f64 = { git = "https://github.com/robtfm/rapier", branch = "master" }
