[package]
name = "decentra-bevy"
version = "0.1.0"
edition = "2021"

[features]
dcl-assert = []
gen-tests = []
tracy = ["bevy/trace_tracy"]

[dependencies]
bevy = { version = "0.10", features=["jpeg"] }
deno_core = "0.183.*"
serde = "1.0.152"
serde_json = { version = "1.0.92", features = ["raw_value"] }
num-traits = "0.2"
num-derive = "0.3"
num = "0.4"
futures-lite = "1.12.0"
itertools = "0.10.5"
tokio = { version = "1.26.0", features = ["sync"] }
once_cell = "1.16.0"
protobuf = "3.2.0"
prost = "0.11.8"
rapier3d = "0.17.2"
nalgebra = { version = "0.32.2", features = [ "convert-glam023" ] }
bimap = "0.6.3"
bevy_prototype_debug_lines = { version = "0.10.1", features = ["3d"] }
bevy_common_assets = { version = "0.6.0", features = ["json"] }
isahc = { version = "1.7.2", features = ["json"] }
pico-args = "0.5.0"
anyhow = "1.0.70"
urlencoding = "2.1.2"
urn = "0.7.0"
bevy_console = "0.7.0"
clap = "4.1.10"
bevy_atmosphere = "0.6.0"
petgraph = "0.6.3"
# requires local version due to once_cell version conflict. probably resolved by updating deno
# bevy_mod_debugdump = { path = "../bevy_mod_debugdump" }

[dev-dependencies]
petgraph = "0.6.3"

[build-dependencies]
prost-build = "0.11.8"
