[package]
name = "dcl"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
common = { path="../common" }
dcl_component = { path="../dcl_component" }
ipfs = { path="../ipfs" }

bevy = "0.10"
tokio = { version = "1.29.1", features = ["sync"] }
once_cell = "1.16.0"
deno_core = "0.183.*"
futures-lite = "1.12.0"
num-derive = "0.3"
num = "0.4"
num-traits = "0.2"
