[package]
name = "dcl"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
common = { workspace = true }
dcl_component = { workspace = true }
ipfs = { workspace = true }
wallet = { workspace = true }

bevy = { workspace = true }
tokio = { workspace = true }
once_cell = { workspace = true }
futures-lite = { workspace = true }
isahc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

deno_core = "0.204"
deno_fetch = "0.142"
deno_webidl = "0.118"
deno_web = "0.149"
deno_url = "0.118"
deno_console = "0.118"
deno_websocket = "0.123"
num-derive = "0.3"
num = "0.4"
num-traits = "0.2"
http = "0.2.9"
bytes = "1.4.0"