[package]
name = "visuals"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
common = { workspace = true }
console = { workspace = true }
bevy = { workspace = true }

bevy_atmosphere = "0.9"
bevy_console = { workspace = true }

clap = { workspace = true }
