[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
bevy = "0.10"
ethers = "2.0.3"
futures-lite = "1.12.0"
hex = "0.4.3"
tokio = { version = "1.26.0", features = ["sync"] }
serde = "1.0.152"
