[package]
name = "comms"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
common = "0.1"
dcl = "0.1"
dcl_component = "0.1"
ipfs = "0.1"

bevy = "0.10"
bimap = "0.6.3"
ethers = "2.0.3"
tokio = { version = "1.26.0", features = ["sync"] }
serde = "1.0.152"
serde_json = { version = "1.0.92", features = ["raw_value"] }
async-trait = "0.1.68"
anyhow = "1.0.70"
async-tungstenite = { version = "0.22.0", features = ["async-std-runtime", "async-tls"] }
async-std = "1.12.0"
async-tls = "0.12.0"
futures-util = "0.3.28"
futures-lite = "1.12.0"
isahc = { version = "1.7.2", features = ["json"] }
prost = "0.11.8"
