[package]
name = "comms"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
common = { workspace = true }
dcl = { workspace = true }
dcl_component = { workspace = true }
ipfs = { workspace = true }

bevy = { workspace = true }
bimap = { workspace = true }
ethers = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
futures-lite = { workspace = true }
isahc = { workspace = true}
prost = { workspace = true}

async-trait = "0.1.68"
async-tungstenite = { version = "0.22.0", features = ["async-std-runtime", "async-tls"] }
async-std = "1.12.0"
async-tls = "0.12.0"
futures-util = "0.3.28"
livekit = { git = "https://github.com/robtfm/client-sdk-rust", branch="h264-false", features=["native-tls"] }
# livekit = { path = "../../../client-sdk-rust/livekit", features=["native-tls"] }
# TODO move to workspace
bevy_kira_audio = { version= "0.16", features=["flac", "mp3", "ogg", "wav"] }
kira = "*"