name: Build Release

on:
    workflow_dispatch:

jobs:
    build:
        name: Build macos aarch64
        runs-on: ubuntu-22.04
        steps:
          - name: Clone repo
            uses: actions/checkout@v3

          - name: qemu  
            uses: uraimo/run-on-arch-action@v2
            id: build
            with:
              arch: aarch64
              distro: ubuntu22.04
              run: |
                /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                brew install pkg-config ffmpeg rust
                cargo build --release