name: Build Release

on:
    workflow_dispatch:

jobs:
    build:
        name: Build macos aarch64
        runs-on: ubuntu-18.04
        steps:
          - name: Clone repo
            uses: actions/checkout@v3

          - name: qemu  
            uses: uraimo/run-on-arch-action@v2
            id: build
            with:
              arch: aarch64
              distro: ubuntu18.04
              run: |
                brew install pkg-config ffmpeg rust
                cargo build --release